//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAnalisis2G8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida_Diario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partida_Diario()
        {
            this.Detalle_Partida_Diario = new HashSet<Detalle_Partida_Diario>();
        }
    
        public int id_partida { get; set; }
        public string correlativo { get; set; }
        public string num_documento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Partida_Diario> Detalle_Partida_Diario { get; set; }
    }
}
